
peline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        S3_BUCKET = 'task-manager7'
        CLOUDFRONT_DISTRIBUTION_ID = 'E17PETT8G2VOVG'
    }

    stages {
        stage('checkout') {
            steps {
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/taskmanager.git'
            }
        }

        stage('install dependencies') {
            steps {
                dir('frontend') {
                sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                withCredentials([file(credentialsId: 'tm-env-prod', variable: 'ENV_PROD')]) {
                    dir('frontend') {
                        sh '''
                            cp $ENV_PROD .env.production
                            npm run build
                        '''
                    }
                }
            }
        }
        stage ('Deploy to s3') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]) {
                sh "/usr/local/bin/aws s3 sync frontend/build/ s3://${S3_BUCKET} --delete"

                }
            }

        }
        stage('invalidate cloudfront cache'){
            steps{
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]) {
                sh "/usr/local/bin/aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'"
                }
            }
        }

    }

}}
