pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        S3_BUCKET = 'jvlcart'
        CLOUDFRONT_DISTRIBUTION_ID = 'E2KYFYDLVUJO6N'
        REACT_APP_API_URL = 'http://54.198.204.21:5000/'
    }

    stages {
        stage('checkout') {
            steps {
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/taskmanager.git'
            }
        }

        stage('install npm dependencies') {
            steps {
                sh 'REACT_APP_API_URL=$REACT_APP_API_URL npm install'
            }
        }

        stage('npm run build'){
            steps {
                sh 'npm run build'
            }
        }

        stage ('move build satic files to s3 bucket'){
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]) {
                sh '/usr/local/bin/aws s3 sync frontend/build/ s3://${S3_BUCKET} --delete'
                }
                
            }
        }
        stage('invalidate cloudfront cache'){
            steps{
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]) {
                sh '/usr/local/bin/aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"'
                }
            }
        } 

    }

}
