pipeline {
    agent any

    environment {
        EC2_HOST = 'ubuntu@54.198.204.21'
        APP_DIR = '/home/ubuntu/taskmanager/'
        APP_PORT = '5000'
        IMAGE = 'backend'
        CONTAINER = 'backend'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/taskmanager.git'
            }
        }

        stage('Copy Code to EC2') {
            steps {
                sshagent(['sshkey-cred']) {
			sh "rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --exclude='frontend' ./backend/ ${EC2_HOST}:${APP_DIR}"
                }
            }
        }

        stage('Build Docker Image on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh"ssh -o StrictHostKeyChecking=no ${EC2_HOST} 'cd ${APP_DIR} && docker build -t ${IMAGE} .'"
                }
            }
        }

        stage('Run Docker Container on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} '
                        docker stop ${CONTAINER} || true
                        docker rm ${CONTAINER} || true
                        docker run -d --name ${CONTAINER} -p ${APP_PORT}:${APP_PORT} --env-file ${APP_DIR}/.env --restart always ${IMAGE}
                        '
                    """

                }
            }
        }
    }
}
