pipeline {
    agent any

    environment {
        EC2_HOST = 'ubuntu@54.198.204.21'
        APP_PORT = '5000'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/taskmanager.git'
            }
        }

        stage('Copy Code to EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='frontend' ./backend/ ${EC2_HOST}:/home/ubuntu/taskmanager/
                    '''
                }
            }
        }

        stage('Build Docker Image on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} "
                            cd /home/ubuntu/taskmanager
                            docker build -t taskmanager-backend:latest .
                        "
                    '''
                }
            }
        }

        stage('Run Docker Container on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} "
                            docker stop backend || true
                            docker rm backend || true

                            docker run -d \
                                --name backend \
                                -p ${APP_PORT}:${APP_PORT} \
                                --env-file /home/ubuntu/taskmanager/.env \
                                --restart always \
                                backend:latest
                        "
                    '''
                }
            }
        }
    }
}
